### ISSUE TITLE
this component does not work!

### ISSUE THREAD

**Issue by maboelsoudd2l** [BrightspaceUI/datetime-picker#66]
for 2 reasons, lemme start with the easy one:
1. no event listeners. which is no biggie, just do this
```javascript
<d2l-date-picker
  on-d2l-date-picker-value-changed="_handleValueChanged"
   // a bunch of shit
  >
```
2. This line https://github.com/BrightspaceUI/datetime-picker/blob/master/d2l-datetime-picker.js#L333 ALWAYS catches because "moment is not defined"

**Comment by AlexBedley** [comment]
The readme states you need to include moment yourself
